// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Sneaker Zone catalog by keyword, brand, category, price range or featured/new flags.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text match on product name or description."),
    brand: z.string().trim().optional().describe("Brand name, e.g. PUMA, Red Tape, Adidas."),
    category: z.string().trim().optional().describe("Product category."),
    max_price: z.number().positive().optional().describe("Maximum sale price in INR."),
    min_price: z.number().nonnegative().optional().describe("Minimum sale price in INR."),
    featured_only: z.boolean().optional().describe("Only return featured products."),
    new_only: z.boolean().optional().describe("Only return newly added products."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_public_products");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const q = input.query?.toLowerCase();
    const rows = (data ?? []).filter((p) => {
      if (q && !`${p.name} ${p.description} ${p.brand}`.toLowerCase().includes(q)) return false;
      if (input.brand && p.brand.toLowerCase() !== input.brand.toLowerCase()) return false;
      if (input.category && p.category.toLowerCase() !== input.category.toLowerCase()) return false;
      if (input.max_price !== void 0 && p.price > input.max_price) return false;
      if (input.min_price !== void 0 && p.price < input.min_price) return false;
      if (input.featured_only && !p.is_featured) return false;
      if (input.new_only && !p.is_new) return false;
      return true;
    }).slice(0, input.limit ?? 20);
    const products = rows.map((p) => ({
      id: p.id,
      name: p.name,
      brand: p.brand,
      category: p.category,
      price_inr: p.price,
      mrp_inr: p.original_price,
      discount_percentage: p.discount_percentage,
      sizes: p.sizes,
      colors: p.colors,
      url: `https://sneaker-zone.lovable.app/product/${p.id}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { count: products.length, products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Get full details and images for one Sneaker Zone product by id or slug.",
  inputSchema: {
    id: z2.number().int().positive().optional().describe("Numeric product id."),
    slug: z2.string().trim().optional().describe("Product slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (id === void 0 && !slug) {
      return { content: [{ type: "text", text: "Provide either id or slug." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_public_products");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const product = (data ?? []).find(
      (p) => id !== void 0 && p.id === id || slug && p.slug === slug
    );
    if (!product) {
      return { content: [{ type: "text", text: "Product not found." }], isError: true };
    }
    const { data: images } = await supabase.from("product_images").select("url, alt, sort_order").eq("product_id", product.id).order("sort_order");
    const result = {
      id: product.id,
      name: product.name,
      slug: product.slug,
      brand: product.brand,
      category: product.category,
      price_inr: product.price,
      mrp_inr: product.original_price,
      discount_percentage: product.discount_percentage,
      save_amount_inr: product.save_amount,
      sku: product.sku,
      material: product.material,
      sizes: product.sizes,
      colors: product.colors,
      details: product.details,
      description: product.description,
      is_new: product.is_new,
      is_featured: product.is_featured,
      images: images ?? [],
      url: `https://sneaker-zone.lovable.app/product/${product.id}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { product: result }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in customer's Sneaker Zone orders with items and status.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Filter by order status, e.g. confirmed, pending."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, created_at, status, payment_method, subtotal, tax, shipping, total, shipping_full_name, shipping_city, shipping_state, order_items(name, size, quantity, price)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var get_order_default = defineTool4({
  name: "get_order",
  title: "Get order",
  description: "Get one of the signed-in customer's Sneaker Zone orders by order id, with line items.",
  inputSchema: { order_id: z4.string().uuid().describe("The order UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select(
      "id, created_at, status, payment_method, subtotal, tax, shipping, total, shipping_full_name, shipping_phone, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, order_items(name, size, quantity, price, image_url)"
    ).eq("user_id", ctx.getUserId()).eq("id", order_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Order not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nuiaqcktaxrlkdgkapkp";
var mcp_default = defineMcp({
  name: "sneaker-zone",
  title: "Sneaker Zone",
  version: "0.1.0",
  instructions: "Tools for Sneaker Zone, a premium sneaker and streetwear store. Use `search_products` to browse the catalog, `get_product` for full details of one sneaker, and `list_my_orders` / `get_order` to check the signed-in customer's orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_orders_default, get_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
